# Generated by Django 4.2.3 on 2023-07-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
